### ISSUE TITLE
Different powerup effects (e.g. different weapons)

### ISSUE THREAD

**Issue by andersonw** [andersonw/gmtk-jam#2]
Ideas:
-lightning (attack everything in a short range)
-n bullets instead of 1
-homing missiles
-really powerful shotgun that pushes you back when you shoot
-"power down"

**Comment by cluedo** [comment]
"water" gun that shoots faster bullets
"laser" that pierces multiple enemies
explosive bullet "rocket launcher"
gun that shoots bullets that collide with enemy bullets (good defensively)

**Comment by cluedo** [comment]
gun that pushes your character in the other direction
